### ISSUE TITLE
Allow PAUL.yaml to reside in .github folder

### ISSUE THREAD

**Issue by onedr0p** [Spazzy757/paul#59]
**Is your feature request related to a problem? Please describe.**

The root of my repo is already cluttered enough

**Describe the solution you'd like**

Allow PAUL.yaml to live in the .github folder as well as the root.

Thanks for the Paul!

**Comment by Spazzy757** [comment]
Thats an awesome Idea I will look into implementing this next week

**Comment by Spazzy757** [comment]
This should work now, I just need to test it

**Comment by Spazzy757** [comment]
And tested, it seems to work! Thanks for logging the issue 👍

**Comment by onedr0p** [comment]
Great, thanks for helping me declutter the root of my repos 😅
