### ISSUE TITLE
Option to disable notifications when Paul responds or takes action on a PR

### ISSUE THREAD

**Issue by onedr0p** [Spazzy757/paul#61]
**Is your feature request related to a problem? Please describe.**

I am getting Github notifications when I type `/approve` or `/merge` that Paul has taken action. These actions shouldn't warrant a notification.

**Describe the solution you'd like**

Allow an option in `PAUL.yaml` to not notify user, specifically maintainers of the repo.

```yaml
notifications: true  # or false
```

**Additional context**
Not sure if GH API allows for that to be configurable but it would be neat!

**Comment by Spazzy757** [comment]
So I looked into this at a high level, seems that notifications are user-specific i.e I set my notifications for my repo. That being said I read [this](https://webapps.stackexchange.com/questions/119494/disable-notifications-from-github-bots) thread that could be potentially useful. I will keep digging to see if there are solutions

**Comment by Spazzy757** [comment]
Not going to be possible as this is a user-specific thing
